/**
 * SPIKE 0c/0d — JS ↔ native byte-interop verification.
 *
 * Consumes interop_vectors.json (generated by the native app's InteropVectorsTest — REAL lazysodium + web3j
 * output) and proves the JS crypto stack reproduces the native bytes exactly:
 *   1. seed → HKDF-SHA256(salt=zeros32, info=ctx+"-box-v1"/"-sign-v1") → box/sign seed-keypairs (pubkeys EQUAL)
 *   2. a native-sealed {f,b,s} envelope OPENS in JS (crypto_box_seal_open) + its Ed25519 sig verifies
 *   3. the bare order-book Ed25519 detached signature verifies against the native signPk
 *   4. seedrandom privkey → secp256k1 → SAME ETH address as web3j
 * All four passing = the MDS port can be a true interoperating peer. Any failure = NO-GO, fix before building.
 */
const fs = require('fs');
const sodium = require('libsodium-wrappers');
const { hkdf } = require('@noble/hashes/hkdf.js');
const { sha256 } = require('@noble/hashes/sha2.js');
const { ethers } = require('ethers');

const V = JSON.parse(fs.readFileSync(__dirname + '/interop_vectors.json', 'utf8'));

const hex = (u8) => Buffer.from(u8).toString('hex');
const unhex = (h) => new Uint8Array(Buffer.from(h.replace(/^0x/, ''), 'hex'));

/** Same rule as native: 0x → hex bytes, else raw UTF-8 bytes. */
function seedBytes(seed) {
    return seed.startsWith('0x') ? unhex(seed) : new Uint8Array(Buffer.from(seed, 'utf8'));
}

/** Native Hkdf.java equivalent: HKDF-SHA256, salt = 32 zero bytes, info = context string, L = 32. */
function deriveSubSeed(seed, info) {
    return hkdf(sha256, seed, new Uint8Array(32), new Uint8Array(Buffer.from(info, 'utf8')), 32);
}

(async () => {
    await sodium.ready;
    let pass = 0, fail = 0;
    const ok = (name, cond) => { if (cond) { pass++; console.log('  ✅', name); } else { fail++; console.log('  ❌', name); } };

    console.log('— 1. identity derivation (seed × context → box/sign pubkeys) —');
    for (const [key, want] of Object.entries(V.identities)) {
        const [seed, ctx] = key.split('|');
        const boxKp = sodium.crypto_box_seed_keypair(deriveSubSeed(seedBytes(seed), ctx + '-box-v1'));
        const signKp = sodium.crypto_sign_seed_keypair(deriveSubSeed(seedBytes(seed), ctx + '-sign-v1'));
        ok(`${key} boxPk`, hex(boxKp.publicKey) === want.boxPk);
        ok(`${key} signPk`, hex(signKp.publicKey) === want.signPk);
        ok(`${key} publicId`, '0x' + hex(boxKp.publicKey) + hex(signKp.publicKey) === want.publicId);
    }

    console.log('— 2. open a native-sealed envelope + verify its inner signature —');
    {
        const e = V.envelope;
        // recipient = SEED_HEX under usdtswap — re-derive its keys the JS way
        const rSeed = Object.keys(V.identities).find(k => k.startsWith('0x') && k.endsWith('usdtswap')).split('|')[0];
        const rBox = sodium.crypto_box_seed_keypair(deriveSubSeed(seedBytes(rSeed), 'usdtswap-box-v1'));
        const payload = sodium.crypto_box_seal_open(unhex(e.sealedBlobHex), rBox.publicKey, rBox.privateKey);
        const p = JSON.parse(Buffer.from(payload).toString('utf8'));
        ok('sealed blob opens', !!p && !!p.f && !!p.b && !!p.s);
        const plaintext = Buffer.from(unhex(p.b)).toString('utf8');
        ok('plaintext matches', plaintext === e.plaintext);
        ok('from = native sender', p.f === e.senderPublicId);
        // signature covers fromBytes(64) || plaintext, verified with signPk = publicId[32:64]
        const fromBytes = unhex(p.f);
        const signed = new Uint8Array([...fromBytes, ...unhex(p.b)]);
        const signPk = fromBytes.slice(32, 64);
        ok('inner Ed25519 sig verifies', sodium.crypto_sign_verify_detached(unhex(p.s), signed, signPk));
    }

    console.log('— 3. bare order-book Ed25519 detached signature —');
    {
        const s = V.sign;
        const msg = new Uint8Array(Buffer.from(s.message, 'utf8'));
        ok('sig verifies vs native signPk', sodium.crypto_sign_verify_detached(unhex(s.sigHex), msg, unhex(s.signPk)));
    }

    console.log('— 4. ETH address from seedrandom privkey (secp256k1 + keccak) —');
    {
        const w = new ethers.Wallet(V.eth.privKey);
        ok('address matches web3j', w.address.toLowerCase() === V.eth.address.toLowerCase());
    }

    console.log(`\n${fail === 0 ? 'ALL PASS' : 'FAILURES'} — ${pass} passed, ${fail} failed`);
    process.exit(fail === 0 ? 0 : 1);
})();
